version: 2
project_name: relaycat
builds:
  - id: relaycat-unix
    main: ./cmd/relaycat
    binary: relaycat
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/lihongjie0209/relaycat/internal/cli.Version={{.Version}}
      - -X github.com/lihongjie0209/relaycat/internal/cli.Commit={{.Commit}}
      - -X github.com/lihongjie0209/relaycat/internal/cli.Date={{.Date}}
  - id: relaycat-windows
    main: ./cmd/relaycat
    binary: relaycat
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [386, amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/lihongjie0209/relaycat/internal/cli.Version={{.Version}}
      - -X github.com/lihongjie0209/relaycat/internal/cli.Commit={{.Commit}}
      - -X github.com/lihongjie0209/relaycat/internal/cli.Date={{.Date}}
archives:
  - formats: [tar.gz]
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY_NOTICES.md
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
sboms:
  - artifacts: archive
changelog:
  sort: asc
